jobs:
  compile:
    name: Maven compiler
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      name: Checkout repository
      uses: actions/checkout@v2
    - continue-on-error: true
      name: Java 17 setup
      uses: actions/setup-java@v2
      with:
        distribution: adopt
        java-package: jdk
        java-version: '17'
    - continue-on-error: true
      name: Cache Maven packages
      uses: actions/cache@v2
      with:
        key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
        path: ~/.m2
        restore-keys: ${{ runner.os }}-m2
    - continue-on-error: true
      name: Build via Maven
      run: mvn verify -B --file pom.xml -DdisableXmlReport=true
name: Compile and test
on:
  repository_dispatch:
    types: trigger-ga___maven.yml
